// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAUbxt7LZwQieX4vIGkFqgVERq7HK5j78',
    appId: '1:1098131102146:web:06ba62a5042ea07e31de5b',
    messagingSenderId: '1098131102146',
    projectId: 'zspdoho-79021',
    authDomain: 'zspdoho-79021.firebaseapp.com',
    storageBucket: 'zspdoho-79021.appspot.com',
    measurementId: 'G-BEH9P6Y2PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA-b9r5NPIr68rPUj-FreYI-ERrKDCDHA',
    appId: '1:1098131102146:android:de9d65f065eebeef31de5b',
    messagingSenderId: '1098131102146',
    projectId: 'zspdoho-79021',
    storageBucket: 'zspdoho-79021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWFEmRNN3kdJUIodJlB3KbjpqZbmqVpOo',
    appId: '1:1098131102146:ios:1b0952c89991c52931de5b',
    messagingSenderId: '1098131102146',
    projectId: 'zspdoho-79021',
    storageBucket: 'zspdoho-79021.appspot.com',
    iosClientId: '1098131102146-hjc1l7ufk1m9eno3dt4bjr32ej1vmhjl.apps.googleusercontent.com',
    iosBundleId: 'com.zspdoho.myCapstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWFEmRNN3kdJUIodJlB3KbjpqZbmqVpOo',
    appId: '1:1098131102146:ios:cd939b5ff854b7ea31de5b',
    messagingSenderId: '1098131102146',
    projectId: 'zspdoho-79021',
    storageBucket: 'zspdoho-79021.appspot.com',
    iosClientId: '1098131102146-6q0gce8jr8maapsinkqkh759c5ujnig9.apps.googleusercontent.com',
    iosBundleId: 'zspdoho',
  );
}
